name: Feature Request
title: 'Hi: '
description: Write something like "Write an api endpoint that does "..." in the "..." file"
labels: hi
body:
  - type: textarea
    id: description
    attributes:
      label: Details
      description: More details for Sweep
      placeholder: The new endpoint should use the ... class from ... file because it contains ... logic